### ISSUE TITLE
Question about Table. 2 LoRA baseline

### ISSUE THREAD

**Issue by haizhou-shi** [huawei-noah/KD-NLP#7]
Hi, thanks for sharing your code of this amazing paper!

I have a probably naive question regarding the LoRA baseline implementation. How did you find the low-rank matrix in table to accommodate small-device deployment? Was it done by selecting the first r vectors in LoRA? 

Thanks for your response in advance.

**Comment by mojivalipour** [comment]
Hi @haizhou-shi, thanks for your interest. I am not sure if I fully understand your question. But if I want to guess, you are trying to choose the most optimal rank based on the device budget. In general, LoRA is not the ideal algorithm for the low-budget deployment but let's say you don't want to use any low-quality models and you are tight with the LoRA. Then in that case, if I were you, I am going to use the elbow method to find the most optimal rank after using DyLoRA to train multiple ranks. You can simply plot the performance-rank (or even flops potentially) figure and you will choose the most optimal one based on your need and your tolerance towards the quality loss.

**Comment by haizhou-shi** [comment]
Hi @mojivalipour!

Thank you for your timely response! Yes I understand how DyLoRA could be a perfect fit for finding an even lower-rank parameters for low-budget devices by choosing the most important ranks at the beginning. 

The thing I'm confused is Table. 2 is reported. To be more specific, how does the performance of LoRA in that table is computed? For example, in the first section: if we know the rank of the edge device is 1, how is the LoRA method yielded? Why is rank-1 LoRA outperformed by DyLoRA first-rank component by such a large margin (30%) in terms of acc.? 

Thanks again!

**Comment by mojivalipour** [comment]
@haizhou-shi In Table 2, the assumption is the fixed training time budget. With an equal training budget, you can either chose to train a LoRA with maximum rank (rank=8 in the experiment) or use the DyLoRA training method. As shown in the table, the performance of the LoRA module that has been trained solely for maximum rank will face significant drop for the lower ranks as we expect. In this experiment, we just wanted to show in an equal training budget how one can choose to train multiple ranks simultaneously instead of a single rank. One might argue, however, that I don't have any limit on my training budget and therefore I can train many LoRA modules with different ranks. In that case, you can check Table 5 of the paper. Regarding to your question, if we know already rank-1 is our best option then there is no point to use DyLoRA because you can simply train a LoRA module with rank 1. However, if you don't know whether rank 1 is a better option or rank 16 then DyLoRA might help you. Hope that answered your question.

**Comment by haizhou-shi** [comment]
@mojivalipour Thanks for the clarification. 

If I understand it correctly, if we do not previously know what rank the edge device can run, but we have a max rank for training (maybe 8?), then for LoRA baseline in Table 2, we evenly split the training quota (machines or time) for different rank of training (train rank 1-8 LoRA simultaneously) and then choose the corresponding rank when deploying it to edge device. 

Just a random thought on a possibly reasonable baseline for LoRA in this case: have you tried do maximum rank training on LoRA and then do a simple SVD to get a lower-rank LoRA for deployment? 

Best,

**Comment by mojivalipour** [comment]
@haizhou-shi For the LoRA baseline in Table 2, we allocated all the training budget to the maximum rank (rank=8). If you divide the budget evenly between all ranks, then the performance of your maximum rank will be significantly less if you don't use weight sharing, which is what we do in DyLoRA.

> Just a random thought on a possibly reasonable baseline for LoRA in this case: have you tried do maximum rank training on LoRA and then do a simple SVD to get a lower-rank LoRA for deployment?

I think it's a valid baseline worth checking. The only concern is the time complexity of SVD.

**Comment by haizhou-shi** [comment]
@mojivalipour Thank you so much for the timely response! 

Thanks again for the great work. I will close the issue.
